version: '3.8'
services:
  #PHP Backend Service
  backend_app:
    container_name: php-larajobs
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: 'larajobs_backend'
    restart: always
    ports:
      - '8001:80'
    volumes:
      - ./backend/:/var/www/html/backend
    networks:
      - app-network

  #Vue Frontend Service
  frontend_app:
    container_name: vue-larajobs
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: 'larajobs_frontend'
    restart: always
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/var/www/html/frontend
      - /var/www/html/frontend/node_modules
    networks:
      - app-network

  #MySQL Service
  database_app:
    container_name: mysql-larajobs
    image: mysql:5.7
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=larajobs
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=larajobs
      - MYSQL_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge